	ECE385 u0 (
		.clk_clk                (<connected-to-clk_clk>),                //             clk.clk
		.io_hex_export          (<connected-to-io_hex_export>),          //          io_hex.export
		.io_keys_export         (<connected-to-io_keys_export>),         //         io_keys.export
		.io_led_green_export    (<connected-to-io_led_green_export>),    //    io_led_green.export
		.io_led_red_export      (<connected-to-io_led_red_export>),      //      io_led_red.export
		.io_switches_export     (<connected-to-io_switches_export>),     //     io_switches.export
		.keycode_export         (<connected-to-keycode_export>),         //         keycode.export
		.nios2_pll_sdram_clk    (<connected-to-nios2_pll_sdram_clk>),    // nios2_pll_sdram.clk
		.otg_hpi_address_export (<connected-to-otg_hpi_address_export>), // otg_hpi_address.export
		.otg_hpi_cs_export      (<connected-to-otg_hpi_cs_export>),      //      otg_hpi_cs.export
		.otg_hpi_data_in_port   (<connected-to-otg_hpi_data_in_port>),   //    otg_hpi_data.in_port
		.otg_hpi_data_out_port  (<connected-to-otg_hpi_data_out_port>),  //                .out_port
		.otg_hpi_r_export       (<connected-to-otg_hpi_r_export>),       //       otg_hpi_r.export
		.otg_hpi_reset_export   (<connected-to-otg_hpi_reset_export>),   //   otg_hpi_reset.export
		.otg_hpi_w_export       (<connected-to-otg_hpi_w_export>),       //       otg_hpi_w.export
		.reset_reset_n          (<connected-to-reset_reset_n>),          //           reset.reset_n
		.sdram_addr             (<connected-to-sdram_addr>),             //           sdram.addr
		.sdram_ba               (<connected-to-sdram_ba>),               //                .ba
		.sdram_cas_n            (<connected-to-sdram_cas_n>),            //                .cas_n
		.sdram_cke              (<connected-to-sdram_cke>),              //                .cke
		.sdram_cs_n             (<connected-to-sdram_cs_n>),             //                .cs_n
		.sdram_dq               (<connected-to-sdram_dq>),               //                .dq
		.sdram_dqm              (<connected-to-sdram_dqm>),              //                .dqm
		.sdram_ras_n            (<connected-to-sdram_ras_n>),            //                .ras_n
		.sdram_we_n             (<connected-to-sdram_we_n>),             //                .we_n
		.sram_sram_addr         (<connected-to-sram_sram_addr>),         //            sram.sram_addr
		.sram_sram_ce_n         (<connected-to-sram_sram_ce_n>),         //                .sram_ce_n
		.sram_sram_dq           (<connected-to-sram_sram_dq>),           //                .sram_dq
		.sram_sram_lb_n         (<connected-to-sram_sram_lb_n>),         //                .sram_lb_n
		.sram_sram_oe_n         (<connected-to-sram_sram_oe_n>),         //                .sram_oe_n
		.sram_sram_ub_n         (<connected-to-sram_sram_ub_n>),         //                .sram_ub_n
		.sram_sram_we_n         (<connected-to-sram_sram_we_n>),         //                .sram_we_n
		.vga_vga_r              (<connected-to-vga_vga_r>),              //             vga.vga_r
		.vga_vga_g              (<connected-to-vga_vga_g>),              //                .vga_g
		.vga_vga_b              (<connected-to-vga_vga_b>),              //                .vga_b
		.vga_vga_drawx          (<connected-to-vga_vga_drawx>),          //                .vga_drawx
		.vga_vga_drawy          (<connected-to-vga_vga_drawy>),          //                .vga_drawy
		.nios2_pll_vga_clk      (<connected-to-nios2_pll_vga_clk>)       //   nios2_pll_vga.clk
	);

