# TCL File Generated by Component Editor 18.1
# Wed May 08 22:50:08 CST 2019
# DO NOT MODIFY


# 
# eth_mac_1g_rgmii "eth_mac_1g_rgmii" v1.0
#  2019.05.08.22:50:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module eth_mac_1g_rgmii
# 
set_module_property DESCRIPTION ""
set_module_property NAME eth_mac_1g_rgmii
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME eth_mac_1g_rgmii
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eth_mac_1g_rgmii
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file eth_mac_1g_rgmii.v VERILOG PATH ../rtl/eth_mac_1g_rgmii.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter TARGET STRING GENERIC
set_parameter_property TARGET DEFAULT_VALUE GENERIC
set_parameter_property TARGET DISPLAY_NAME TARGET
set_parameter_property TARGET TYPE STRING
set_parameter_property TARGET UNITS None
set_parameter_property TARGET HDL_PARAMETER true
add_parameter IODDR_STYLE STRING IODDR2
set_parameter_property IODDR_STYLE DEFAULT_VALUE IODDR2
set_parameter_property IODDR_STYLE DISPLAY_NAME IODDR_STYLE
set_parameter_property IODDR_STYLE TYPE STRING
set_parameter_property IODDR_STYLE UNITS None
set_parameter_property IODDR_STYLE HDL_PARAMETER true
add_parameter CLOCK_INPUT_STYLE STRING BUFIO2
set_parameter_property CLOCK_INPUT_STYLE DEFAULT_VALUE BUFIO2
set_parameter_property CLOCK_INPUT_STYLE DISPLAY_NAME CLOCK_INPUT_STYLE
set_parameter_property CLOCK_INPUT_STYLE TYPE STRING
set_parameter_property CLOCK_INPUT_STYLE UNITS None
set_parameter_property CLOCK_INPUT_STYLE HDL_PARAMETER true
add_parameter USE_CLK90 STRING TRUE
set_parameter_property USE_CLK90 DEFAULT_VALUE TRUE
set_parameter_property USE_CLK90 DISPLAY_NAME USE_CLK90
set_parameter_property USE_CLK90 TYPE STRING
set_parameter_property USE_CLK90 UNITS None
set_parameter_property USE_CLK90 HDL_PARAMETER true
add_parameter ENABLE_PADDING INTEGER 1
set_parameter_property ENABLE_PADDING DEFAULT_VALUE 1
set_parameter_property ENABLE_PADDING DISPLAY_NAME ENABLE_PADDING
set_parameter_property ENABLE_PADDING TYPE INTEGER
set_parameter_property ENABLE_PADDING UNITS None
set_parameter_property ENABLE_PADDING HDL_PARAMETER true
add_parameter MIN_FRAME_LENGTH INTEGER 64
set_parameter_property MIN_FRAME_LENGTH DEFAULT_VALUE 64
set_parameter_property MIN_FRAME_LENGTH DISPLAY_NAME MIN_FRAME_LENGTH
set_parameter_property MIN_FRAME_LENGTH TYPE INTEGER
set_parameter_property MIN_FRAME_LENGTH UNITS None
set_parameter_property MIN_FRAME_LENGTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point tx_axis
# 
add_interface tx_axis axi4stream end
set_interface_property tx_axis associatedClock ""
set_interface_property tx_axis associatedReset ""
set_interface_property tx_axis ENABLED true
set_interface_property tx_axis EXPORT_OF ""
set_interface_property tx_axis PORT_NAME_MAP ""
set_interface_property tx_axis CMSIS_SVD_VARIABLES ""
set_interface_property tx_axis SVD_ADDRESS_GROUP ""

add_interface_port tx_axis tx_axis_tdata tdata Input 8
add_interface_port tx_axis tx_axis_tvalid tvalid Input 1
add_interface_port tx_axis tx_axis_tready tready Output 1
add_interface_port tx_axis tx_axis_tuser tuser Input 1
add_interface_port tx_axis tx_axis_tlast tlast Input 1


# 
# connection point rx_axis
# 
add_interface rx_axis axi4stream start
set_interface_property rx_axis associatedClock ""
set_interface_property rx_axis associatedReset ""
set_interface_property rx_axis ENABLED true
set_interface_property rx_axis EXPORT_OF ""
set_interface_property rx_axis PORT_NAME_MAP ""
set_interface_property rx_axis CMSIS_SVD_VARIABLES ""
set_interface_property rx_axis SVD_ADDRESS_GROUP ""

add_interface_port rx_axis rx_axis_tdata tdata Output 8
add_interface_port rx_axis rx_axis_tlast tlast Output 1
add_interface_port rx_axis rx_axis_tuser tuser Output 1
add_interface_port rx_axis rx_axis_tvalid tvalid Output 1


# 
# connection point gtx_clk
# 
add_interface gtx_clk clock end
set_interface_property gtx_clk clockRate 0
set_interface_property gtx_clk ENABLED true
set_interface_property gtx_clk EXPORT_OF ""
set_interface_property gtx_clk PORT_NAME_MAP ""
set_interface_property gtx_clk CMSIS_SVD_VARIABLES ""
set_interface_property gtx_clk SVD_ADDRESS_GROUP ""

add_interface_port gtx_clk gtx_clk clk Input 1


# 
# connection point gtx_clk90
# 
add_interface gtx_clk90 clock end
set_interface_property gtx_clk90 clockRate 0
set_interface_property gtx_clk90 ENABLED true
set_interface_property gtx_clk90 EXPORT_OF ""
set_interface_property gtx_clk90 PORT_NAME_MAP ""
set_interface_property gtx_clk90 CMSIS_SVD_VARIABLES ""
set_interface_property gtx_clk90 SVD_ADDRESS_GROUP ""

add_interface_port gtx_clk90 gtx_clk90 clk Input 1


# 
# connection point gtx_rst
# 
add_interface gtx_rst reset end
set_interface_property gtx_rst associatedClock gtx_clk
set_interface_property gtx_rst synchronousEdges DEASSERT
set_interface_property gtx_rst ENABLED true
set_interface_property gtx_rst EXPORT_OF ""
set_interface_property gtx_rst PORT_NAME_MAP ""
set_interface_property gtx_rst CMSIS_SVD_VARIABLES ""
set_interface_property gtx_rst SVD_ADDRESS_GROUP ""

add_interface_port gtx_rst gtx_rst reset Input 1


# 
# connection point rgmii
# 
add_interface rgmii conduit end
set_interface_property rgmii associatedClock gtx_clk
set_interface_property rgmii associatedReset ""
set_interface_property rgmii ENABLED true
set_interface_property rgmii EXPORT_OF ""
set_interface_property rgmii PORT_NAME_MAP ""
set_interface_property rgmii CMSIS_SVD_VARIABLES ""
set_interface_property rgmii SVD_ADDRESS_GROUP ""

add_interface_port rgmii rgmii_rx_clk rgmii_rx_clk Input 1
add_interface_port rgmii rgmii_rxd rgmii_rxd Input 4
add_interface_port rgmii rgmii_rx_ctl rgmii_rx_ctl Input 1
add_interface_port rgmii rgmii_tx_clk rgmii_tx_clk Output 1
add_interface_port rgmii rgmii_txd rgmii_txd Output 4
add_interface_port rgmii rgmii_tx_ctl rgmii_tx_ctl Output 1


# 
# connection point status
# 
add_interface status conduit end
set_interface_property status associatedClock gtx_clk
set_interface_property status associatedReset ""
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status tx_error_underflow tx_error_underflow Output 1
add_interface_port status rx_error_bad_frame rx_error_bad_frame Output 1
add_interface_port status rx_error_bad_fcs rx_error_bad_fcs Output 1
add_interface_port status speed speed Output 2


# 
# connection point config
# 
add_interface config conduit end
set_interface_property config associatedClock gtx_clk
set_interface_property config associatedReset ""
set_interface_property config ENABLED true
set_interface_property config EXPORT_OF ""
set_interface_property config PORT_NAME_MAP ""
set_interface_property config CMSIS_SVD_VARIABLES ""
set_interface_property config SVD_ADDRESS_GROUP ""

add_interface_port config ifg_delay ifg_delay Input 8


# 
# connection point rx_clk
# 
add_interface rx_clk clock start
set_interface_property rx_clk associatedDirectClock ""
set_interface_property rx_clk clockRate 0
set_interface_property rx_clk clockRateKnown false
set_interface_property rx_clk ENABLED true
set_interface_property rx_clk EXPORT_OF ""
set_interface_property rx_clk PORT_NAME_MAP ""
set_interface_property rx_clk CMSIS_SVD_VARIABLES ""
set_interface_property rx_clk SVD_ADDRESS_GROUP ""

add_interface_port rx_clk rx_clk clk Output 1


# 
# connection point tx_clk
# 
add_interface tx_clk clock start
set_interface_property tx_clk associatedDirectClock ""
set_interface_property tx_clk clockRate 0
set_interface_property tx_clk clockRateKnown false
set_interface_property tx_clk ENABLED true
set_interface_property tx_clk EXPORT_OF ""
set_interface_property tx_clk PORT_NAME_MAP ""
set_interface_property tx_clk CMSIS_SVD_VARIABLES ""
set_interface_property tx_clk SVD_ADDRESS_GROUP ""

add_interface_port tx_clk tx_clk clk Output 1


# 
# connection point rx_rst
# 
add_interface rx_rst reset start
set_interface_property rx_rst associatedClock gtx_clk
set_interface_property rx_rst associatedDirectReset ""
set_interface_property rx_rst associatedResetSinks ""
set_interface_property rx_rst synchronousEdges DEASSERT
set_interface_property rx_rst ENABLED true
set_interface_property rx_rst EXPORT_OF ""
set_interface_property rx_rst PORT_NAME_MAP ""
set_interface_property rx_rst CMSIS_SVD_VARIABLES ""
set_interface_property rx_rst SVD_ADDRESS_GROUP ""

add_interface_port rx_rst rx_rst reset Output 1


# 
# connection point tx_rst
# 
add_interface tx_rst reset start
set_interface_property tx_rst associatedClock gtx_clk
set_interface_property tx_rst associatedDirectReset ""
set_interface_property tx_rst associatedResetSinks ""
set_interface_property tx_rst synchronousEdges DEASSERT
set_interface_property tx_rst ENABLED true
set_interface_property tx_rst EXPORT_OF ""
set_interface_property tx_rst PORT_NAME_MAP ""
set_interface_property tx_rst CMSIS_SVD_VARIABLES ""
set_interface_property tx_rst SVD_ADDRESS_GROUP ""

add_interface_port tx_rst tx_rst reset Output 1

